/* File: "trigger_takeoff_altitude_violation_arg_13.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 5412",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_5412[ptr_5412]);
*/
SInt64 trigger_takeoff_altitude_violation_arg_13(const SInt64 *queue_5412,
                                                 const SWord32 ptr_5412)
{
  const SInt64  s0 = queue_5412[0];
  const SInt64  s1 = queue_5412[1];
  const SInt64  s2 = queue_5412[2];
  const SInt64  s3 = queue_5412[3];
  const SWord32 s4 = ptr_5412;
  const SInt64 table0[] = {
      s0, s1, s2, s3
  };
  const SWord32 s6 = (0x00000004UL == 0) ? s4 : (s4 % 0x00000004UL);
  const SInt64  s7 = table0[s6];

  return s7;
}
