/* File: "trigger_takeoff_altitude_violation_arg_15.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 5414",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_5414[ptr_5414]);
*/
SInt64 trigger_takeoff_altitude_violation_arg_15(const SInt64 *queue_5414,
                                                 const SWord32 ptr_5414)
{
  const SInt64  s0 = queue_5414[0];
  const SInt64  s1 = queue_5414[1];
  const SInt64  s2 = queue_5414[2];
  const SWord32 s3 = ptr_5414;
  const SInt64 table0[] = {
      s0, s1, s2
  };
  const SWord32 s5 = (0x00000003UL == 0) ? s3 : (s3 % 0x00000003UL);
  const SInt64  s6 = table0[s5];

  return s6;
}
