/* File: "trigger_takeoff_altitude_violation_arg_6.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 5405",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_5405[ptr_5405]);
*/
SDouble trigger_takeoff_altitude_violation_arg_6(const SDouble *queue_5405,
                                                 const SWord32 ptr_5405)
{
  const SDouble s0 = queue_5405[0];
  const SDouble s1 = queue_5405[1];
  const SDouble s2 = queue_5405[2];
  const SDouble s3 = queue_5405[3];
  const SDouble s4 = queue_5405[4];
  const SDouble s5 = queue_5405[5];
  const SDouble s6 = queue_5405[6];
  const SWord32 s7 = ptr_5405;
  const SDouble table0[] = {
      s0, s1, s2, s3, s4, s5, s6
  };
  const SWord32 s9 = (0x00000007UL == 0) ? s7 : (s7 % 0x00000007UL);
  const SDouble s10 = table0[s9];

  return s10;
}
