/* File: "trigger_takeoff_altitude_violation_arg_10.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 003*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 5409",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_5409[ptr_5409]);
*/
SDouble trigger_takeoff_altitude_violation_arg_10(const SDouble *queue_5409,
                                                  const SWord32 ptr_5409)
{
  const SDouble s0 = queue_5409[0];
  const SDouble s1 = queue_5409[1];
  const SDouble s2 = queue_5409[2];
  const SDouble s3 = queue_5409[3];
  const SDouble s4 = queue_5409[4];
  const SWord32 s5 = ptr_5409;
  const SDouble table0[] = {
      s0, s1, s2, s3, s4
  };
  const SWord32 s7 = (0x00000005UL == 0) ? s5 : (s5 % 0x00000005UL);
  const SDouble s8 = table0[s7];

  return s8;
}
