/* File: "update_state_2.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="op2: <",color=green4, style=filled]
0 -> 1
2 [label="ext_altitude_ft",color=cyan1, style=filled]
1 -> 2
3 [label="const: 5000.0",color=red1, style=filled]
1 -> 3


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (((ext_altitude_ft) < (5000.0)));
*/
SBool update_state_2(const SDouble ext_altitude_ft)
{
  const SDouble s0 = ext_altitude_ft;
  const SBool   s2 = s0 < 5000.0;

  return s2;
}
