/* File: "update_state_791.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 788",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_788[0]);
*/
SBool update_state_791(const SBool *queue_788,
                       const SWord32 ptr_788)
{
  const SBool   s0 = queue_788[0];
  return s0;
}
