/* File: "update_state_3376.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 3373",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_3373[0]);
*/
SBool update_state_3376(const SBool *queue_3373,
                        const SWord32 ptr_3373)
{
  const SBool   s0 = queue_3373[0];
  return s0;
}
