/* File: "update_state_455.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 452",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_452[0]);
*/
SBool update_state_455(const SBool *queue_452,
                       const SWord32 ptr_452)
{
  const SBool   s0 = queue_452[0];
  return s0;
}
