/* File: "update_state_2906.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 2903",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_2903[0]);
*/
SBool update_state_2906(const SBool *queue_2903,
                        const SWord32 ptr_2903)
{
  const SBool   s0 = queue_2903[0];
  return s0;
}
