/* File: "update_state_292.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 289",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_289[0]);
*/
SBool update_state_292(const SBool *queue_289,
                       const SWord32 ptr_289)
{
  const SBool   s0 = queue_289[0];
  return s0;
}
