/* File: "update_state_86.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 83",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_83[0]);
*/
SBool update_state_86(const SBool *queue_83, const SWord32 ptr_83)
{
  const SBool   s0 = queue_83[0];
  return s0;
}
