/* File: "update_state_470.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 467",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_467[0]);
*/
SBool update_state_470(const SBool *queue_467,
                       const SWord32 ptr_467)
{
  const SBool   s0 = queue_467[0];
  return s0;
}
