/* File: "update_state_401.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 398",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_398[0]);
*/
SBool update_state_401(const SBool *queue_398,
                       const SWord32 ptr_398)
{
  const SBool   s0 = queue_398[0];
  return s0;
}
