/* File: "update_state_671.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 668",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_668[0]);
*/
SBool update_state_671(const SBool *queue_668,
                       const SWord32 ptr_668)
{
  const SBool   s0 = queue_668[0];
  return s0;
}
