/* File: "update_state_2408.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 2405",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_2405[0]);
*/
SBool update_state_2408(const SBool *queue_2405,
                        const SWord32 ptr_2405)
{
  const SBool   s0 = queue_2405[0];
  return s0;
}
