/* File: "update_state_2948.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 2945",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_2945[0]);
*/
SBool update_state_2948(const SBool *queue_2945,
                        const SWord32 ptr_2945)
{
  const SBool   s0 = queue_2945[0];
  return s0;
}
