/* File: "update_state_3895.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 3892",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_3892[0]);
*/
SBool update_state_3895(const SBool *queue_3892,
                        const SWord32 ptr_3892)
{
  const SBool   s0 = queue_3892[0];
  return s0;
}
