/* File: "update_state_392.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 389",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_389[0]);
*/
SBool update_state_392(const SBool *queue_389,
                       const SWord32 ptr_389)
{
  const SBool   s0 = queue_389[0];
  return s0;
}
