/* File: "update_state_551.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 548",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_548[0]);
*/
SBool update_state_551(const SBool *queue_548,
                       const SWord32 ptr_548)
{
  const SBool   s0 = queue_548[0];
  return s0;
}
