/* File: "update_state_2453.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 2450",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_2450[0]);
*/
SBool update_state_2453(const SBool *queue_2450,
                        const SWord32 ptr_2450)
{
  const SBool   s0 = queue_2450[0];
  return s0;
}
