/* File: "update_state_887.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 884",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_884[0]);
*/
SBool update_state_887(const SBool *queue_884,
                       const SWord32 ptr_884)
{
  const SBool   s0 = queue_884[0];
  return s0;
}
