/* File: "update_state_2572.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 2569",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_2569[0]);
*/
SBool update_state_2572(const SBool *queue_2569,
                        const SWord32 ptr_2569)
{
  const SBool   s0 = queue_2569[0];
  return s0;
}
