/* File: "update_state_338.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 335",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_335[0]);
*/
SBool update_state_338(const SBool *queue_335,
                       const SWord32 ptr_335)
{
  const SBool   s0 = queue_335[0];
  return s0;
}
