/* File: "update_state_4150.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 4147",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_4147[0]);
*/
SBool update_state_4150(const SBool *queue_4147,
                        const SWord32 ptr_4147)
{
  const SBool   s0 = queue_4147[0];
  return s0;
}
