/* File: "update_state_52.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 49",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_49[0]);
*/
SBool update_state_52(const SBool *queue_49, const SWord32 ptr_49)
{
  const SBool   s0 = queue_49[0];
  return s0;
}
