/* File: "update_state_1001.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 998",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_998[0]);
*/
SBool update_state_1001(const SBool *queue_998,
                        const SWord32 ptr_998)
{
  const SBool   s0 = queue_998[0];
  return s0;
}
