/* File: "update_state_309.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 306",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_306[0]);
*/
SInt64 update_state_309(const SInt64 *queue_306,
                        const SWord32 ptr_306)
{
  const SInt64  s0 = queue_306[0];
  return s0;
}
