/* File: "update_state_922.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 919",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_919[0]);
*/
SBool update_state_922(const SBool *queue_919,
                       const SWord32 ptr_919)
{
  const SBool   s0 = queue_919[0];
  return s0;
}
