/* File: "update_state_5095.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 5092",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_5092[0]);
*/
SBool update_state_5095(const SBool *queue_5092,
                        const SWord32 ptr_5092)
{
  const SBool   s0 = queue_5092[0];
  return s0;
}
