/* File: "update_state_4891.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 4888",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_4888[0]);
*/
SBool update_state_4891(const SBool *queue_4888,
                        const SWord32 ptr_4888)
{
  const SBool   s0 = queue_4888[0];
  return s0;
}
