/* File: "update_state_4117.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 4114",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_4114[0]);
*/
SBool update_state_4117(const SBool *queue_4114,
                        const SWord32 ptr_4114)
{
  const SBool   s0 = queue_4114[0];
  return s0;
}
