/* File: "update_state_5189.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 5186",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_5186[0]);
*/
SBool update_state_5189(const SBool *queue_5186,
                        const SWord32 ptr_5186)
{
  const SBool   s0 = queue_5186[0];
  return s0;
}
