/* File: "update_state_263.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 260",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_260[0]);
*/
SBool update_state_263(const SBool *queue_260,
                       const SWord32 ptr_260)
{
  const SBool   s0 = queue_260[0];
  return s0;
}
