/* File: "update_state_136.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 133",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_133[0]);
*/
SBool update_state_136(const SBool *queue_133,
                       const SWord32 ptr_133)
{
  const SBool   s0 = queue_133[0];
  return s0;
}
