/* File: "update_state_164.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 161",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_161[0]);
*/
SBool update_state_164(const SBool *queue_161,
                       const SWord32 ptr_161)
{
  const SBool   s0 = queue_161[0];
  return s0;
}
