/* File: "update_state_5014.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 5011",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_5011[0]);
*/
SBool update_state_5014(const SBool *queue_5011,
                        const SWord32 ptr_5011)
{
  const SBool   s0 = queue_5011[0];
  return s0;
}
