/* File: "update_state_3767.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 3764",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_3764[0]);
*/
SBool update_state_3767(const SBool *queue_3764,
                        const SWord32 ptr_3764)
{
  const SBool   s0 = queue_3764[0];
  return s0;
}
