/* File: "update_state_2753.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 2750",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_2750[0]);
*/
SBool update_state_2753(const SBool *queue_2750,
                        const SWord32 ptr_2750)
{
  const SBool   s0 = queue_2750[0];
  return s0;
}
