/* File: "update_state_938.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 935",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_935[0]);
*/
SBool update_state_938(const SBool *queue_935,
                       const SWord32 ptr_935)
{
  const SBool   s0 = queue_935[0];
  return s0;
}
