/* File: "update_state_1937.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 1934",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_1934[0]);
*/
SBool update_state_1937(const SBool *queue_1934,
                        const SWord32 ptr_1934)
{
  const SBool   s0 = queue_1934[0];
  return s0;
}
