/* File: "update_state_752.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 749",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_749[0]);
*/
SBool update_state_752(const SBool *queue_749,
                       const SWord32 ptr_749)
{
  const SBool   s0 = queue_749[0];
  return s0;
}
