/* File: "update_state_3169.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 3166",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_3166[0]);
*/
SBool update_state_3169(const SBool *queue_3166,
                        const SWord32 ptr_3166)
{
  const SBool   s0 = queue_3166[0];
  return s0;
}
