/* File: "update_state_661.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 658",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_658[0]);
*/
SBool update_state_661(const SBool *queue_658,
                       const SWord32 ptr_658)
{
  const SBool   s0 = queue_658[0];
  return s0;
}
