/* File: "update_state_715.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 712",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_712[0]);
*/
SBool update_state_715(const SBool *queue_712,
                       const SWord32 ptr_712)
{
  const SBool   s0 = queue_712[0];
  return s0;
}
