/* File: "update_state_953.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 950",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_950[0]);
*/
SBool update_state_953(const SBool *queue_950,
                       const SWord32 ptr_950)
{
  const SBool   s0 = queue_950[0];
  return s0;
}
