/* File: "update_state_118.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 115",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_115[0]);
*/
SBool update_state_118(const SBool *queue_115,
                       const SWord32 ptr_115)
{
  const SBool   s0 = queue_115[0];
  return s0;
}
