/* File: "update_state_1415.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 1412",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_1412[0]);
*/
SBool update_state_1415(const SBool *queue_1412,
                        const SWord32 ptr_1412)
{
  const SBool   s0 = queue_1412[0];
  return s0;
}
