/* File: "update_state_5104.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 5101",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_5101[0]);
*/
SBool update_state_5104(const SBool *queue_5101,
                        const SWord32 ptr_5101)
{
  const SBool   s0 = queue_5101[0];
  return s0;
}
