/* File: "update_state_133.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 130",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_130[0]);
*/
SBool update_state_133(const SBool *queue_130,
                       const SWord32 ptr_130)
{
  const SBool   s0 = queue_130[0];
  return s0;
}
