/* File: "update_state_1652.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 1649",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_1649[0]);
*/
SBool update_state_1652(const SBool *queue_1649,
                        const SWord32 ptr_1649)
{
  const SBool   s0 = queue_1649[0];
  return s0;
}
