/* File: "update_state_796.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 793",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_793[0]);
*/
SBool update_state_796(const SBool *queue_793,
                       const SWord32 ptr_793)
{
  const SBool   s0 = queue_793[0];
  return s0;
}
