/* File: "update_state_157.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 154",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_154[0]);
*/
SBool update_state_157(const SBool *queue_154,
                       const SWord32 ptr_154)
{
  const SBool   s0 = queue_154[0];
  return s0;
}
