/* File: "update_state_878.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 875",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_875[0]);
*/
SBool update_state_878(const SBool *queue_875,
                       const SWord32 ptr_875)
{
  const SBool   s0 = queue_875[0];
  return s0;
}
