/* File: "update_state_3674.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 3671",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_3671[0]);
*/
SBool update_state_3674(const SBool *queue_3671,
                        const SWord32 ptr_3671)
{
  const SBool   s0 = queue_3671[0];
  return s0;
}
