/* File: "update_state_847.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 844",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_844[0]);
*/
SBool update_state_847(const SBool *queue_844,
                       const SWord32 ptr_844)
{
  const SBool   s0 = queue_844[0];
  return s0;
}
