/* File: "update_state_562.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 559",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_559[0]);
*/
SBool update_state_562(const SBool *queue_559,
                       const SWord32 ptr_559)
{
  const SBool   s0 = queue_559[0];
  return s0;
}
