/* File: "update_state_913.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 910",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_910[0]);
*/
SBool update_state_913(const SBool *queue_910,
                       const SWord32 ptr_910)
{
  const SBool   s0 = queue_910[0];
  return s0;
}
