/* File: "update_state_220.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 217",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_217[0]);
*/
SBool update_state_220(const SBool *queue_217,
                       const SWord32 ptr_217)
{
  const SBool   s0 = queue_217[0];
  return s0;
}
