/* File: "update_state_2210.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 2207",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_2207[0]);
*/
SBool update_state_2210(const SBool *queue_2207,
                        const SWord32 ptr_2207)
{
  const SBool   s0 = queue_2207[0];
  return s0;
}
