/* File: "update_state_653.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 650",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_650[0]);
*/
SBool update_state_653(const SBool *queue_650,
                       const SWord32 ptr_650)
{
  const SBool   s0 = queue_650[0];
  return s0;
}
