/* File: "update_state_4088.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 4085",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_4085[0]);
*/
SBool update_state_4088(const SBool *queue_4085,
                        const SWord32 ptr_4085)
{
  const SBool   s0 = queue_4085[0];
  return s0;
}
