/* File: "update_state_2090.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 2087",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_2087[0]);
*/
SBool update_state_2090(const SBool *queue_2087,
                        const SWord32 ptr_2087)
{
  const SBool   s0 = queue_2087[0];
  return s0;
}
