/* File: "update_state_3572.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 3569",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_3569[0]);
*/
SBool update_state_3572(const SBool *queue_3569,
                        const SWord32 ptr_3569)
{
  const SBool   s0 = queue_3569[0];
  return s0;
}
