/* File: "update_state_799.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 796",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_796[0]);
*/
SBool update_state_799(const SBool *queue_796,
                       const SWord32 ptr_796)
{
  const SBool   s0 = queue_796[0];
  return s0;
}
