/* File: "update_state_3578.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 3575",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_3575[0]);
*/
SBool update_state_3578(const SBool *queue_3575,
                        const SWord32 ptr_3575)
{
  const SBool   s0 = queue_3575[0];
  return s0;
}
