/* File: "update_state_1301.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 1298",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_1298[0]);
*/
SBool update_state_1301(const SBool *queue_1298,
                        const SWord32 ptr_1298)
{
  const SBool   s0 = queue_1298[0];
  return s0;
}
