/* File: "update_state_2110.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 2107",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_2107[0]);
*/
SBool update_state_2110(const SBool *queue_2107,
                        const SWord32 ptr_2107)
{
  const SBool   s0 = queue_2107[0];
  return s0;
}
