/* File: "update_state_823.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 820",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_820[0]);
*/
SBool update_state_823(const SBool *queue_820,
                       const SWord32 ptr_820)
{
  const SBool   s0 = queue_820[0];
  return s0;
}
