/* File: "update_state_542.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 539",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_539[0]);
*/
SBool update_state_542(const SBool *queue_539,
                       const SWord32 ptr_539)
{
  const SBool   s0 = queue_539[0];
  return s0;
}
