/* File: "update_state_598.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 595",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_595[0]);
*/
SBool update_state_598(const SBool *queue_595,
                       const SWord32 ptr_595)
{
  const SBool   s0 = queue_595[0];
  return s0;
}
