/* File: "update_state_2912.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 2909",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_2909[0]);
*/
SBool update_state_2912(const SBool *queue_2909,
                        const SWord32 ptr_2909)
{
  const SBool   s0 = queue_2909[0];
  return s0;
}
