/* File: "update_state_877.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 874",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_874[0]);
*/
SBool update_state_877(const SBool *queue_874,
                       const SWord32 ptr_874)
{
  const SBool   s0 = queue_874[0];
  return s0;
}
