/* File: "update_state_519.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 516",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_516[0]);
*/
SInt64 update_state_519(const SInt64 *queue_516,
                        const SWord32 ptr_516)
{
  const SInt64  s0 = queue_516[0];
  return s0;
}
