/* File: "update_state_3311.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 3308",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_3308[0]);
*/
SBool update_state_3311(const SBool *queue_3308,
                        const SWord32 ptr_3308)
{
  const SBool   s0 = queue_3308[0];
  return s0;
}
