/* File: "update_state_235.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 232",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_232[0]);
*/
SBool update_state_235(const SBool *queue_232,
                       const SWord32 ptr_232)
{
  const SBool   s0 = queue_232[0];
  return s0;
}
