/* File: "update_state_1255.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 1252",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_1252[0]);
*/
SBool update_state_1255(const SBool *queue_1252,
                        const SWord32 ptr_1252)
{
  const SBool   s0 = queue_1252[0];
  return s0;
}
