/* File: "update_state_4105.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 4102",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_4102[0]);
*/
SBool update_state_4105(const SBool *queue_4102,
                        const SWord32 ptr_4102)
{
  const SBool   s0 = queue_4102[0];
  return s0;
}
