/* File: "update_state_875.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 872",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_872[0]);
*/
SBool update_state_875(const SBool *queue_872,
                       const SWord32 ptr_872)
{
  const SBool   s0 = queue_872[0];
  return s0;
}
