/* File: "update_state_4138.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 4135",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_4135[0]);
*/
SBool update_state_4138(const SBool *queue_4135,
                        const SWord32 ptr_4135)
{
  const SBool   s0 = queue_4135[0];
  return s0;
}
