/* File: "update_state_3070.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 3067",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_3067[0]);
*/
SBool update_state_3070(const SBool *queue_3067,
                        const SWord32 ptr_3067)
{
  const SBool   s0 = queue_3067[0];
  return s0;
}
