/* File: "update_state_5093.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 5090",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_5090[0]);
*/
SBool update_state_5093(const SBool *queue_5090,
                        const SWord32 ptr_5090)
{
  const SBool   s0 = queue_5090[0];
  return s0;
}
