/* File: "update_state_867.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 864",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_864[0]);
*/
SInt64 update_state_867(const SInt64 *queue_864,
                        const SWord32 ptr_864)
{
  const SInt64  s0 = queue_864[0];
  return s0;
}
