/* File: "update_state_326.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 323",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_323[0]);
*/
SBool update_state_326(const SBool *queue_323,
                       const SWord32 ptr_323)
{
  const SBool   s0 = queue_323[0];
  return s0;
}
