/* File: "update_state_1159.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 1156",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_1156[0]);
*/
SBool update_state_1159(const SBool *queue_1156,
                        const SWord32 ptr_1156)
{
  const SBool   s0 = queue_1156[0];
  return s0;
}
