/* File: "update_state_172.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 169",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_169[0]);
*/
SBool update_state_172(const SBool *queue_169,
                       const SWord32 ptr_169)
{
  const SBool   s0 = queue_169[0];
  return s0;
}
