/* File: "update_state_4673.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 4670",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_4670[0]);
*/
SBool update_state_4673(const SBool *queue_4670,
                        const SWord32 ptr_4670)
{
  const SBool   s0 = queue_4670[0];
  return s0;
}
