/* File: "update_state_3008.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 3005",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_3005[0]);
*/
SBool update_state_3008(const SBool *queue_3005,
                        const SWord32 ptr_3005)
{
  const SBool   s0 = queue_3005[0];
  return s0;
}
