/* File: "update_state_98.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 95",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_95[0]);
*/
SBool update_state_98(const SBool *queue_95, const SWord32 ptr_95)
{
  const SBool   s0 = queue_95[0];
  return s0;
}
