/* File: "update_state_4631.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 4628",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_4628[0]);
*/
SBool update_state_4631(const SBool *queue_4628,
                        const SWord32 ptr_4628)
{
  const SBool   s0 = queue_4628[0];
  return s0;
}
