/* File: "update_state_4717.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 4714",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_4714[0]);
*/
SBool update_state_4717(const SBool *queue_4714,
                        const SWord32 ptr_4714)
{
  const SBool   s0 = queue_4714[0];
  return s0;
}
