/* File: "update_state_82.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 79",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_79[0]);
*/
SBool update_state_82(const SBool *queue_79, const SWord32 ptr_79)
{
  const SBool   s0 = queue_79[0];
  return s0;
}
