/* File: "update_state_4253.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 4250",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_4250[0]);
*/
SBool update_state_4253(const SBool *queue_4250,
                        const SWord32 ptr_4250)
{
  const SBool   s0 = queue_4250[0];
  return s0;
}
