/* File: "update_state_764.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 761",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_761[0]);
*/
SBool update_state_764(const SBool *queue_761,
                       const SWord32 ptr_761)
{
  const SBool   s0 = queue_761[0];
  return s0;
}
