/* File: "update_state_5270.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 5267",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_5267[0]);
*/
SBool update_state_5270(const SBool *queue_5267,
                        const SWord32 ptr_5267)
{
  const SBool   s0 = queue_5267[0];
  return s0;
}
