/* File: "update_state_1444.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 1441",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_1441[0]);
*/
SBool update_state_1444(const SBool *queue_1441,
                        const SWord32 ptr_1441)
{
  const SBool   s0 = queue_1441[0];
  return s0;
}
