/* File: "update_state_946.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 943",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_943[0]);
*/
SBool update_state_946(const SBool *queue_943,
                       const SWord32 ptr_943)
{
  const SBool   s0 = queue_943[0];
  return s0;
}
