/* File: "update_state_218.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 215",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_215[0]);
*/
SBool update_state_218(const SBool *queue_215,
                       const SWord32 ptr_215)
{
  const SBool   s0 = queue_215[0];
  return s0;
}
