/* File: "update_state_4310.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 4307",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_4307[0]);
*/
SBool update_state_4310(const SBool *queue_4307,
                        const SWord32 ptr_4307)
{
  const SBool   s0 = queue_4307[0];
  return s0;
}
