/* File: "update_state_935.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 932",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_932[0]);
*/
SBool update_state_935(const SBool *queue_932,
                       const SWord32 ptr_932)
{
  const SBool   s0 = queue_932[0];
  return s0;
}
