/* File: "update_state_73.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 70",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_70[0]);
*/
SBool update_state_73(const SBool *queue_70, const SWord32 ptr_70)
{
  const SBool   s0 = queue_70[0];
  return s0;
}
