/* File: "update_state_649.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 646",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_646[0]);
*/
SBool update_state_649(const SBool *queue_646,
                       const SWord32 ptr_646)
{
  const SBool   s0 = queue_646[0];
  return s0;
}
