/* File: "update_state_4756.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 4753",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_4753[0]);
*/
SBool update_state_4756(const SBool *queue_4753,
                        const SWord32 ptr_4753)
{
  const SBool   s0 = queue_4753[0];
  return s0;
}
