/* File: "update_state_3410.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 3407",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_3407[0]);
*/
SBool update_state_3410(const SBool *queue_3407,
                        const SWord32 ptr_3407)
{
  const SBool   s0 = queue_3407[0];
  return s0;
}
