/* File: "update_state_3976.c". Automatically generated by SBV. Do not edit! */

#include "internal.h"

/* User given declarations: */
/*test 001*/
/*DotBegin
digraph G {
node [shape=box]

0 [label="file: 
?????",color=red, style=filled]
1 [label="stream: 3973",color=crimson, style=filled]
0 -> 1


}

DotEnd*/
/*@
 assigns \nothing;
 ensures \result == (queue_3973[0]);
*/
SBool update_state_3976(const SBool *queue_3973,
                        const SWord32 ptr_3973)
{
  const SBool   s0 = queue_3973[0];
  return s0;
}
